<a href="https://colab.research.google.com/github/yashveersinghsohi/Hands_On_ML_Book_Practice/blob/master/Chapter_4/Practice_Chapter4_Training_Models.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Importing Packages

In [23]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.datasets import load_boston
from sklearn.linear_model import (
    LinearRegression, 
    SGDRegressor
  )
from sklearn.preprocessing import (
    StandardScaler, 
    PolynomialFeatures
  )
from tqdm import tqdm

# Data

In [2]:
boston = load_boston()

# Linear Regression using Normal Equation

Data

In [3]:
X, y = boston.data, boston.target
X_b = np.c_[np.ones(shape=(X.shape[0], 1)), X]

Normal Equation

In [4]:
theta_best = np.dot(np.dot(np.linalg.pinv(np.dot(X_b.T, X_b)), X_b.T), y)
theta_best

array([ 3.64594884e+01, -1.08011358e-01,  4.64204584e-02,  2.05586264e-02,
        2.68673382e+00, -1.77666112e+01,  3.80986521e+00,  6.92224641e-04,
       -1.47556685e+00,  3.06049479e-01, -1.23345939e-02, -9.52747232e-01,
        9.31168327e-03, -5.24758378e-01])

Predict

In [5]:
X_predict = X_b[0]
y_hat = np.dot(theta_best, X_predict)
y_hat, y[0]

(30.003843377084745, 24.0)

# Linear Regression using Sklearn

Model

In [6]:
lin_reg = LinearRegression()
lin_reg.fit(X, y)
lin_reg.intercept_, lin_reg.coef_

(36.459488385090125,
 array([-1.08011358e-01,  4.64204584e-02,  2.05586264e-02,  2.68673382e+00,
        -1.77666112e+01,  3.80986521e+00,  6.92224640e-04, -1.47556685e+00,
         3.06049479e-01, -1.23345939e-02, -9.52747232e-01,  9.31168327e-03,
        -5.24758378e-01]))

Predict

In [7]:
X_predict = X[0]
y_hat = lin_reg.predict([X_predict])
y_hat, y[0]

(array([30.00384338]), 24.0)

# Stochastic Gradient Descent

Data

In [9]:
X, y = boston.data, boston.target
X_b = np.c_[np.ones(shape=(X.shape[0], 1)), X]
X_b.shape, y.shape

((506, 14), (506,))

Scaling

In [19]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

Model

In [20]:
sgd_reg = SGDRegressor(penalty=None, eta0=0.01, max_iter=1000, tol=1e-3)
sgd_reg.fit(X_scaled, y)
sgd_reg.intercept_, sgd_reg.coef_

(array([22.56576539]),
 array([-0.8898178 ,  0.99126234, -0.14443074,  0.73970392, -1.92072259,
         2.78826381, -0.06868451, -3.00329024,  1.97474331, -1.38701321,
        -2.03721949,  0.85816604, -3.73306066]))

Predictions

In [22]:
X_predict = X_scaled[0]
y_hat = sgd_reg.predict([X_predict])
y_hat, y[0]

(array([30.57324757]), 24.0)

# Polynomial Regression

Data

In [24]:
X, y = boston.data, boston.target
X_b = np.c_[np.ones(shape=(X.shape[0], 1)), X]

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

Adding Polynomial Features

In [26]:
poly_features = PolynomialFeatures(degree=2, include_bias=False)
X_poly = poly_features.fit_transform(X_scaled)
X_scaled.shape, X_poly.shape

((506, 13), (506, 104))

Model

In [27]:
lin_reg = LinearRegression()
lin_reg.fit(X_poly, y)
lin_reg.intercept_, lin_reg.coef_

(679434669252.3757,
 array([ 1.59234951e+01,  1.50502515e+01,  9.36622159e+00,  2.30722377e+12,
        -1.87308397e+00,  3.51318636e+00, -2.09148102e+00, -2.49408286e+00,
         5.12328230e+00, -1.01107633e+01,  1.18145533e+00,  1.43242023e+00,
        -3.16190626e+00,  1.16426626e-01,  4.34139171e+01,  2.32192411e+01,
         5.43302795e+00, -7.15031736e-01,  8.28190784e-01, -7.48693468e-01,
        -1.72395548e+00,  1.60313434e+01, -3.47896325e+01,  7.14658242e+00,
        -2.55511066e-01,  1.27309309e+00, -2.62819140e-01, -8.27610903e-01,
        -3.69842439e-01, -2.82159275e+00,  2.23447724e-01,  4.88085530e-02,
        -5.04200936e-01, -1.01763916e+00,  2.49133301e+00, -3.52333069e-01,
         1.38286972e+00, -7.49053955e-01,  1.85934448e+00,  1.43432617e-03,
         9.49054718e-01,  1.42794800e+00,  6.67434692e-01,  1.92483521e+00,
        -1.37421227e+00,  6.52282715e-01, -1.96197510e-01,  1.53338623e+00,
        -5.54687500e-01, -6.79434669e+11, -1.00100708e+00, -9.833984

Predictions

In [29]:
X_predict = X_poly[0]
y_hat = lin_reg.predict([X_predict])
y_hat, y[0]

(array([24.78417969]), 24.0)

# Learning Curves